### ISSUE TITLE
Azure IoT Centralが開かない場合がある

### ISSUE THREAD

**Issue by greennote** [algyan/touch_and_try-ReButton#10]
第1章で https://apps.azureiotcentral.com を開くよう指示がありますが、以下の場合はリンクが開かない場合があることを確認しました。

* 環境
  * macOS Mojave 10.14.4 (18E226)
  * Safari バージョン12.1 (14607.1.40.1.4)
* 状況
  * Azureにログインしていない状態で、
  * 上記URLをアドレスバーにコピー&ペーストしてエンターキーを押す

発生する現象はかなり複雑で、下記のいずれかの事象が発生します。
1. リダイレクトが発生せず、何も表示されない
1. azure login画面へリダイレクトされるが、何も表示されない
1. azure login画面へリダイレクトされ、正常に表示される。ログインもできる
1. エラーメッセージが出る
    ```
    {
        "code": "502.540.999.002",
        "message": "Bad gateway"
    }
    ```

エラーメッセージは、もしかするとこの作業を繰り返して行ったので攻撃と判断されたのかもしれません。

**Comment by greennote** [comment]
Chromeでは今のところこのような問題は見られないようなので、macで参加する人にはそちらを使ってもらう方がいいかもしれません。

**Comment by matsujirushi** [comment]
FYI
他に事象発生しないか、スレッドへ問い合わせした。

**Comment by y-ohe** [comment]
Win7SP1 Firefox Quantum 66.0.5(64bit)では、普通にリダイレクトし、ログインできました。
Safariは、？？？
(ずいぶん古いMacはあるのですが、最近ネットにも繋がず、bootcampのWin10マシンになっています・・)

**Comment by zukoudan** [comment]
一応ためしはしましたが、OS(10.11.2)もSafari(9.0.2(11601.3.9))もバージョンが古く参考にはならなそうです。状況的にはログインはできていて「新しいアプリケーションの作成」は押せますが次の画面で料金プランが正常な表示になりません。

**Comment by matsujirushi** [comment]
|macOS|Safari|結果|テスター|
|:--|:--|:--|:--|
|10.14.4|12.1|×|greennote|
|10.14.5|12.1.1|×|greennote|
|10.14.3|12.0.3|〇|(kogure)|
|10.11.2|9.0.2|〇|zukoudan|
|10.14.5|12.1.1|〇？|(kogure)|

**Comment by matsujirushi** [comment]
操作を繰り返せばログインできるようなので、これを回避策とします。
