### ISSUE TITLE
Azureサブスクリプションの事前作成

### ISSUE THREAD

**Issue by greennote** [algyan/touch_and_try-ReButton#12]
第1章でIoT Centralアプリケーションを作成する際、事前にサブスクリプションを作成しておく必要があります。これはConnpassの募集文でも明記されているので問題ないと思うのですが、作業を忘れてくる人（あるいは、やり方がわからなくてできなかった人）へのガイドがあると良いかと思います。

**Comment by matsujirushi** [comment]
FYI
外部サイトへのリンクを追加しようと思います。
良さそうなサイトを知らないので、IoTあるじゃん運営に問い合わせした。

**Comment by matsujirushi** [comment]
会場にサポートエンジニアがいるようなので、その方にフォローしてもらう。
