### ISSUE TITLE
IoTC: クリック種類別のカラー指定方法がわかりにくい

### ISSUE THREAD

**Issue by greennote** [algyan/touch_and_try-ReButton#13]
### IoTC : 測定項目にクリック種類を追加

のところで、カラーを指定／変更する作業について記載がないのでわかりにくいです。少なくとも

* マニュアルにあるRGB値を直接入力することはできない
* カーソルをカラーチャートの上にホバーし、表示されるRGB値が同じものを選ぶ

というくらいの説明は必要かと思います。

**Comment by y-ohe** [comment]
「⑥カラー」の指定に対する補足説明を追記しました。
また、参考設定色を見た目でも識別しやすくなるように、表中に実際のRGB値を指定した色文字表示を追加したのですが、github側がhtmlタグを受け付けず、ダメでした。
↓
カラーテーブルをキャプチャし、画像を差し込みます。

**Comment by y-ohe** [comment]
カラーパレット表示画面をキャプチャし、差し替え(img/37.png)しました。
これに伴い、img/original-img.pptxをも更新しています。
