### ISSUE TITLE
IoTC: 複数カラーの指定方法がわかりにくい

### ISSUE THREAD

**Issue by greennote** [algyan/touch_and_try-ReButton#14]
### IoTC : 測定項目にクリック種類を追加

のところで、クリック種別ごとにカラーを指定していく作業がありますが、複数のカラーを割り当てる方法がわかりにくいです。色ごとに「③[+]をクリック」する作業を繰り返す、ということが明確になるような書き方が良いかと思います。

**Comment by y-ohe** [comment]
設定を繰り返すことを強調するように表現を見直しました。
