### ISSUE TITLE
VS codeのインストールで必要な拡張機能(Extensions)が説明できていない。

### ISSUE THREAD

**Issue by y-ohe** [algyan/touch_and_try-ReButton#16]
4章からVS codeを使うシナリオになっている中、VS codeのインストールに必要な拡張機能(extensions)が説明できていまい。
必要なのは、
・Azure Extension Pack
・Azure Functions
ぐらい？

connpass募集ページにも記載が必要!!

**Comment by matsujirushi** [comment]
Azure上にWindows 10 Enterpriseを立てて、下記をインストール後、4章が実施できるか確認しました。

* Visual Studio Code
* [Azure Functions Extension](https://marketplace.visualstudio.com/items?itemName=ms-azuretools.vscode-azurefunctions)

1. C#を選択した後、.NET CLIが必要な旨のエラーが表示されました。

![image](https://user-images.githubusercontent.com/8079404/57854076-4bf3c980-7822-11e9-94ef-8d33b2b0a342.png)

→ .NET Core 2.2 SDKをインストールして対処した。  
![image](https://user-images.githubusercontent.com/8079404/57854156-73e32d00-7822-11e9-99c7-6af1fe3f5db1.png)

2. いくつかrecommendが表示されました。

![image](https://user-images.githubusercontent.com/8079404/57854208-9bd29080-7822-11e9-894b-702880a28870.png)


→無視

**Comment by matsujirushi** [comment]
[イベントページ](https://algyan.connpass.com/event/130744/)の事前準備に追記した。
