### ISSUE TITLE
3章のキャプチャ画像の「Manage actions」が現時点では「アクションの管理」になっている

### ISSUE THREAD

**Issue by y-ohe** [algyan/touch_and_try-ReButton#17]
![image](https://user-images.githubusercontent.com/18491913/57902931-a898c800-78a6-11e9-8631-c6149c5ed34e.png)

**Comment by y-ohe** [comment]
差し替える場合、差し替えが必要な画像は48.png～52.pngの5枚です。

**Comment by matsujirushi** [comment]
都度、追従するのは大変なので、このままでOKです。
