### ISSUE TITLE
「IoTC : デバイステンプレートを作成」説明文に対する提案

### ISSUE THREAD

**Issue by zukoudan** [algyan/touch_and_try-ReButton#18]
早とちりする(僕みたいな)人向けに、ダッシュボードにあるCreate Device Templateボタン(アイコン?)ではなく、「左柱のメニューにあるデバイス テンプレート」をクリックすることに注意を促す短文があるといいかもしれません。
(最終結果は同じようですし、取り越し苦労かもしれませんが)

**Comment by matsujirushi** [comment]
> https://github.com/algyan/touch_and_try-ReButton#iotc--%E3%83%87%E3%83%90%E3%82%A4%E3%82%B9%E3%83%86%E3%83%B3%E3%83%97%E3%83%AC%E3%83%BC%E3%83%88%E3%82%92%E4%BD%9C%E6%88%90

「左の①デバイステンプレートをクリックしてください。」が書いてあり、かつ、図だけでも①→②であることがわかるので、このままにします。
