### ISSUE TITLE
「作成したReButtonデバイスが表示されます。」どこに表示されるか

### ISSUE THREAD

**Issue by zukoudan** [algyan/touch_and_try-ReButton#19]
行186「作成したReButtonデバイスが表示されます。」の部分で、文面から、その画面のどこかにデバイスを示す何か(アイコンやボタン等)が表示される印象を受けたため、しばらく探してしまったのですが、その画面全体がデバイスの画面であると分かる文章になっていると分かりやすいかもしれません。

**Comment by matsujirushi** [comment]
@zukoudan 
次の対処でどうでしょうか？

* 「作成したReButtonデバイスの画面に切り替わります。」と記入。
* 次の図の「デバイス ReButton #1」に赤線を引いておく

**Comment by zukoudan** [comment]
分かりやすくなるとおもいますので、いい案と思います。
赤線のところは赤囲みでもいいかもしれません。
