### ISSUE TITLE
「成功するまで、ボタンを押し直してください」で設定確認の必要性

### ISSUE THREAD

**Issue by zukoudan** [algyan/touch_and_try-ReButton#20]
行321「成功するまで、ボタンを押し直してください」について、設定が間違っている可能性もあると思いますので、設定の確認についても触れておいていただく方がいいかもしれません。
(IoT CentralにログインしたPCとは別のPCでReButtonの設定を入力し、コピペでなく手入力だったため接続情報が間違っていた、ということがあった)

**Comment by matsujirushi** [comment]
赤色点滅は通知失敗を表していますが、その原因は様々です。
ご指摘のとおり、ボタンの押しなおしで回復しないときもあります。（←むしろ、回復しない場合が多いと思います。）

問合せで多いのは、
1. IoT Hubの設定を削除し忘れ
2. IoT Centralの設定間違い
3. Wi-Fi パスワードの設定間違い
です。

これらを記入したいと思います。

**Comment by zukoudan** [comment]
挙げていただいたチェックポイント、よいと思います。
参加者が自分で間違いに気づけそうです。

**Comment by y-ohe** [comment]
クラウド通知失敗時の説明を括弧文形式から引用形式に変更しました。
(体裁修正のみ)
