### ISSUE TITLE
PCからReButtonへの接続に関する説明文について

### ISSUE THREAD

**Issue by zukoudan** [algyan/touch_and_try-ReButton#21]
行240「接続操作すると、接続試行中のまま時間がかかりますが、接続試行中表示のまま、次の作業に進みます。」で、次の作業に進んでいる間にReButtonへ接続されず、別のネットワークに接続されていて、それに気づかず192.168.0.1への接続を試していた、という状況が数回発生したので、ReButtonへの接続がどうしてもできないときに再度接続先を確認するという注意を入れていただく方がいいかもしれません。
(OSはWindows10で試しました)

**Comment by matsujirushi** [comment]
> 次の作業に進んでいる間にReButtonへ接続されず
接続されない原因は分かりませんか？（推測でも結構です）

**Comment by y-ohe** [comment]
推測ですが、待ちすぎたのだと思います。
待ちすぎて、タイムアウト後に、別のWi-Fi AP(SSID)への接続に自動的に切り替わってしまったという感じかな？

**Comment by zukoudan** [comment]
試していた感じでは、タスクバーの電波アイコン（WiFiアイコン？）をクリックして出てくるポップアップウィンドウを「表示したまま」にしておくと接続される、といった動作に見えました。
(確か上記に思い至った時に、こいつ見てないとサボるんか！などと思っていたはずなので)

ただ、その後ポップアップを表示したまま接続を待つようにしても、頻度は低いですがたまに接続失敗はしています。

他に接続可能なネットワークがある場合で、接続可能なネットワークが「自動的に接続する」だった場合に、そちらに優先して接続する動作なのかもしれません。(←大栄さんの推測とほぼ同じかもですが)

**Comment by y-ohe** [comment]
Wi-Fi接続先が勝手に切り替わる場合があることと、うまくいかないときに再確認する旨を追記しました。
