### ISSUE TITLE
SMS登録時のメッセージについて説明

### ISSUE THREAD

**Issue by greennote** [algyan/touch_and_try-ReButton#24]
携帯電話をSMS送信先として選択すると、添付のような確認メッセージが届くようです。不慣れな方だと驚くかもしれないので説明があると良いと思います。
![IMG_7198](https://user-images.githubusercontent.com/38572686/57991710-978cc880-7aeb-11e9-9560-57fc4261df28.PNG)

**Comment by y-ohe** [comment]
登録完了時のSMS通知キャプチャ画像は入れませんでしたが、通知が届く旨の記載を追加しました。
