### ISSUE TITLE
SMS送信のタイムラグについて

### ISSUE THREAD

**Issue by greennote** [algyan/touch_and_try-ReButton#25]
SMS送信のタイムラグについて、こちらでテストした限りではReButtonを押してからSMS受信まで最大10分掛かりました。

テキストにはちゃんと「デバイステンプレートの測定画面に表示されるタイミングとSMS受信デバイスにメッセージが届くタイミングは、異なります」と説明されているのですが、さすがに10分掛かるとは想像していなかったので、てっきり設定が失敗しているものと思っていろいろ慌ててしまいました。

すごく待つ場合もあるということを、ひとこと添えてあるとよろしいかと思います。

**Comment by greennote** [comment]
その後もテストを続けていますが、最大29分遅れというケースがありました。こうなると、本当にこれが仕様なのか、それとも当方の設定／環境に問題があるのか心配になってしまいます。

**Comment by matsujirushi** [comment]
バックエンドの仕組みは分かりませんので、以下のとおり対応しましょう。

* 「10分以上、時間がかかるときがあります。」と記入
* 通知が極端に遅いときはMSサポートに聞く

**Comment by y-ohe** [comment]
#3-3に追記しました。
