### ISSUE TITLE
Seeed ReButtonのリンク先URLは日本サイトでなくてOKですか？

### ISSUE THREAD

**Issue by tonjiro** [algyan/touch_and_try-ReButton#27]
【タッチアンドトライのゴール】
品名Seeed ReButtonのリンクURL：https://www.seeedstudio.com/ReButton-p-2930.html

**Comment by y-ohe** [comment]
残念ながら、日本のサイトはまだないん(確か)です。

**Comment by matsujirushi** [comment]
Seeed BazaarへのリンクでOK。
（現時点は、日本国内の販売店でReButtonを取り扱っているところは無いです。）
