### ISSUE TITLE
項目名の「ReButton+」の意味

### ISSUE THREAD

**Issue by greennote** [algyan/touch_and_try-ReButton#33]
項目名に

1-6 ReButton : 接続情報を設定
1-7 ReButton+ : ボタンをクリックしてIoT Centralに通知

のような感じで「ReButton」と「ReButton+」がありますが、これはどういう意味でしょうか？

**Comment by y-ohe** [comment]
あっ、これ私も見直しをしていて、気になりました。

**Comment by matsujirushi** [comment]
「ReButton+」は、ReButtonと他の部分（たとえばAzure IoT Central）を使うという意味で、「+」を付けていました。
意味がわからないと指摘いただいたので、「+」を除きます。
