### ISSUE TITLE
「==任意==」の箇所についてコピペできる参考値を提示しても良いかも

### ISSUE THREAD

**Issue by tatsu1225** [algyan/touch_and_try-ReButton#38]
# 提案
入力項目で何度か出てくる「==任意==」の項目について、スクショで提示されている値を「参考値」として提示しても良いかもしれない

## 提案内容
限られた時間内でのハンズオンのようなので、時間内に終える人の達成率を高めるならば，コピペできると操作は早くなると思われる
(ただし，理解度は下がりそう)

## 重要度
低め

## その他
やるとなると項目は多そうなので、そこまで至れり尽くせりでなくても良い気もします

**Comment by y-ohe** [comment]
コピペで良い(本当に何でも良い)部分と、コピペでダメ(ユニークじゃないとダメ)な部分があるので、前者はスクショのテキストを記載するようにします。

**Comment by y-ohe** [comment]
@matsujirushi 
y-ohe-issue38 で処置しました。
マージください。
