### ISSUE TITLE
「1-7 ReButton」にあるブラウザの表示を最新に更新する方法

### ISSUE THREAD

**Issue by tatsu1225** [algyan/touch_and_try-ReButton#39]
## 確認したい事項
> ブラウザでAzure IoT Central上のデバイスReButton #1にイベント通知が届いたか、確認するために、ブラウザの表示を最新に更新します。

これってブラウザのリロードボタン押下のイメージで良いんですか？

## その他
ReButtonが手元にない環境下でのウォークスルーの為、ちと確認です。細かい内容でスンマセン！

**Comment by y-ohe** [comment]
はい、一応自動更新はかかるのですが、ブラウザのリロードボタンクリックをイメージしています。

**Comment by tatsu1225** [comment]
承知です。ありがとうございます！
