### ISSUE TITLE
表フォーマット崩れあり

### ISSUE THREAD

**Issue by zukoudan** [algyan/touch_and_try-ReButton#4]
以下の部分の表記述部です：
![24](img/24.png)

ReButtonのWi-Fi接続設定画面が表示されます。  
下表のとおり設定して、最後に③`Save`をクリックしてください。  
|項目名|値|
|:--|:--|
|①Wi-Fi SSID|`XXXXXXX`をプルダウン候補から選択(当日別途展開します)|
|②Wi-Fi Passphrase|`zzzzzz`(当日別途展開します)|

**Comment by y-ohe** [comment]
update-textのbranch最新で、処置しました。
