### ISSUE TITLE
「2-1 IoTC」の状態作成の際のカラーにマゼンタが無い

### ISSUE THREAD

**Issue by tatsu1225** [algyan/touch_and_try-ReButton#40]
## 確認したい事項
状態を表す色に私の環境だと「マゼンタ」が無い。
参考設定色と記載ありますので、設定できる色は環境に依存する部分があるんでしょうか？

RGB値でカラーを設定できると良さそうですが、見た感じ現状のUIでは出来ないようですね。

**Comment by y-ohe** [comment]
カラーパレットのキャプチャ撮れますか？

**Comment by tatsu1225** [comment]
<img width="899" alt="9818c5a0588ed9bf8efae3256d8cb29a 1" src="https://user-images.githubusercontent.com/7766952/58290812-fd33ca00-7df5-11e9-9a24-f187cb9ff0dd.png">

スンマセン、キャプチャ貼ろうと思って忘れてコミットしてました！！１
こちらです。

**Comment by y-ohe** [comment]
あー、IoT Centoralのテーマ設定で、カラーパレットが変わるんですねー
右上の設定アイコン(歯車アイコン)で、テーマを「ダーク」に切り替えると、設定できるようになります。

**Comment by matsujirushi** [comment]
カラーは指定色に合わせようとすると手間がかかるので、、、
適当な色でも良い旨を追記しようと思います。

**Comment by y-ohe** [comment]
@matsujirushi 
y-ohe-issue40 で処置しました。
PRは出せていませんが、マージください。

**Comment by matsujirushi** [comment]
表現を少し修正しました。
