### ISSUE TITLE
「4-2 VSCode」の際にAzureマークが見当たらない人向けにExtentionsのインストール方法の提示

### ISSUE THREAD

**Issue by tatsu1225** [algyan/touch_and_try-ReButton#41]
# 提案
(VSCodeに使い慣れていない人を想定して、）「4-2 VSCode」の際にAzureマークが見当たらない人向けにExtentionsのインストール方法の提示してあげるとより親切かな。と。
Mustでは無いです．

## 提案内容
Azureマーク(AzureFunctions)のボタンが出るようにExtensionsのインストール方法の提示．
外部サイトなどでも良ければ，そちらへのリンクでも良いかもしれません．

## 重要度
低

## その他
私の環境(Win10, VSCode ver1.34.0)ではAzureマークは別途追加しないとありませんでした

**Comment by y-ohe** [comment]
connpassの募集ページで、VS拡張など事前準備に載せています。
https://algyan.connpass.com/event/130744/

でも、準備状況を確認できる記載は入れておいた方が良いと思うので、処置します。

**Comment by tatsu1225** [comment]
そちらで記載済みだったのですね！承知です。ありがとうございました！

**Comment by y-ohe** [comment]
@matsujirushi 
y-ohe-issue41 で処置しました。
マージしてください。
