### ISSUE TITLE
注意喚起の記述位置を変える提案

### ISSUE THREAD

**Issue by zukoudan** [algyan/touch_and_try-ReButton#5]
以下の記述について、もっと上(「長く押す」です、のすぐ下くらい)に持ってきた方がいいと感じます：
**【注意！】**  
LED(白)になるまで、ボタンを押し続けた場合は、最初の設定で行った`Access Pointモード`になってしまいます。  
この場合は、一度裏ぶたを開けて、電池を抜き差しして、`Access Pointモード`を解除し、元に戻してください。  
(設定済みのWi-Fi情報やAzure IoT Central接続情報も消えてしまいますでの、再度設定をし直す必要があります。)

**Comment by y-ohe** [comment]
記載を提案された位置に修正しました。
(注意喚起を表形式にし、さらに目立つようにしてみました。)
