### ISSUE TITLE
SMS受信までの時間

### ISSUE THREAD

**Issue by micciiii** [algyan/touch_and_try-ReButton#53]
テキストには10分かかる時があると明記されていましたが、
本当に10分ほどかかったので驚きました。
それ以外の部分はとても分かり易かったです。

**Comment by horiken38** [comment]
20分ぐらいかかってました

**Comment by blackdesigntokyo** [comment]
Azureの方にはデータが来ているのに、そこからまた時間がかかるというのに吃驚しました

**Comment by matsujirushi** [comment]
`このSMS通知は10分以上、時間がかかるときがあります。`
という表記があるので、テキストは未修正とします。
