### ISSUE TITLE
画面ショットと説明文のサンドイッチ間隔

### ISSUE THREAD

**Issue by Haruo-san** [algyan/touch_and_try-ReButton#54]
画面ショットと説明文が交互にサンドイッチに連続する場合に、ある説明文が、その上と下のどちらの画面ショットに属するものなのか分かり難い。行の間隔を調整することで、改善されると思います。

**Comment by matsujirushi** [comment]
@y-ohe 説明文→画像、の順で統一されているという認識ですが、合っていますか？

**Comment by y-ohe** [comment]
@matsujirushi はい、合っています。
でも、やはり分かりにくいのですよねー。
言われているように、もう一行ずつ改行を入れるか、各節ごとにつけている水平線を入れるかした方が分かりやすくなるのは確かですね。
