### ISSUE TITLE
Azureサブスクリプションが試用版である場合の”3-2 IoTC : ルールを追加”について

### ISSUE THREAD

**Issue by 344abq** [algyan/touch_and_try-ReButton#56]
Azureが試用版で登録したまま作業を進めると、
項目”3-2 IoTC : ルールを追加”作業時に、
表示されるアクションの選択の中から
②Azure Monitor アクション グループのクリックができません
（従量課金制じゃないと使用不可のようです）

試用版で作業をすすめていたので、電子メールで通知の機能を使って
代替案ではありますが、作業を完了させました。

試用版で作業を進めてしまった人も、携帯等の端末にReButtonからの通知が届くワクワク感を味わうことができると思うので、こちらの代替案もタッチアンドトライの中に一筆書いていただけると良いかなと思いました。

**Comment by matsujirushi** [comment]
# メモ

Azure Subscription登録が上手くいかず、Azure IoT Centralの支払いプランを評価版にして進めたため、アクションの一部機能が利用できなかった。

本テキストは、Azure Subscriptionを利用できる想定。
Azure Subscriptionが使えない場合についても書くか否か判断が必要。

**Comment by matsujirushi** [comment]
@y-ohe ご意見いただけませんか？

**Comment by y-ohe** [comment]
@matsujirushi 「1-1 IOTC：アプリケーションを作成」の手順で、「従量課金制」としてあるので、本質的にはトラブル対策不要だと思っています。
とは言え、トラブルが出ているので、ここの備考欄に「評価版」を選択すると、後の手順で作業が進められない旨を追記しましょうか？

**Comment by matsujirushi** [comment]
@y-ohe 追記をお願いします。

**Comment by y-ohe** [comment]
@matsujirushi 処置してプルリク出しました！
