### ISSUE TITLE
SMS通知の際の時刻がUTC

### ISSUE THREAD

**Issue by gadgetking-y** [algyan/touch_and_try-ReButton#57]
SMSで通知される時刻がUTCなのをJSTにするにはどうすれば良いでしょう？

**Comment by blackdesigntokyo** [comment]
この件は、私も気になりました。

**Comment by matsujirushi** [comment]
Azure MonitorのSMS通知に書かれている時刻のタイムゾーンを変更する方法は無いようです。

■参考
https://feedback.azure.com/forums/357324-azure-monitor-application-insights/suggestions/15517140-display-data-and-reports-in-local-time-not-utc
https://feedback.azure.com/forums/267889-log-analytics/suggestions/6728221-display-in-local-time
