### ISSUE TITLE
章記号 ### のすぐ下にある一言に関する表記変更の提案

### ISSUE THREAD

**Issue by zukoudan** [algyan/touch_and_try-ReButton#6]
章記号### の行のすぐ下に、そのサブセクションの概要が短文で記されていますが、引用表記になっているのは、ぱっと見に何なのかわかりづらいと思いました。
(とはいえ、GitHub Markdownにはこういう場合に適当な表記手段がないようですが)

例えば、「本章の目的：(概要表記)」として、行全体を太字+斜体にする、などではいかがでしょうか。反則だとは思いますが、テーブルで表現という手もあるかと思います。例えば以下など：

|_**目標**_|
|:------|
|Azure IoT Centralのアプリケーションを作成します。|

**Comment by matsujirushi** [comment]
@y-ohe 提案のとおり、テーブル表現が良いと思いますが、どうでしょう？
ご意見ください。

**Comment by y-ohe** [comment]
@matsujirushi @zukoudan 記載済み部分に対し、処置しました。
ただし、タイトルの「目標」がちょっと適切なのか微妙な気もしています。
(「シナリオ」というのもいい気がしていますが、元の表現自体の見直しも必要になりそうなので、最後に時間が取れた場合に見直すことにします。

**Comment by zukoudan** [comment]
目標という語は、自分でも書いておきながら「別の言い回しないかなあ」とは思っていましたので、何か適切な語があれば・・・
参考書などでは「この節の目的」などという言い回しが使われてた気が。ちょっと長いでしょうか・・・

**Comment by y-ohe** [comment]
「この節での実施概要」にしました。
