### ISSUE TITLE
デバイステンプレートの設定方法

### ISSUE THREAD

**Issue by k-maru** [algyan/touch_and_try-ReButton#67]
Azure IoT Central を学習するに際して、非常に参考になりそうだったので手順をたどらせてもらいました。
しかし、デバイステンプレートの追加方法が2020/12現在、大きく変わっているようで、行き詰ってしまいました。

なにか、こうすれば出来るよ、ここを見れば差分で分かるよ、などあればお教え願えれば幸いです。

**Comment by matsujirushi** [comment]
@k-maru さん、こんにちは。
おっしゃる通り、Azure IoT Centralのバージョンアップ（v2→v3）に伴って、操作方法が変わっています。特にデバイステンプレート周辺が。
ReButtonをIoT Plug and Playに対応させたいと思っていますので、手順の変更はその後に行う予定です。

デバイステンプレートの手動設定は、、、早送りですが、こちらが参考になるかと思います。
[Demo: IoT Plug and Play in Azure IoT Central](https://youtu.be/yovI_4yMOhc)

**Comment by k-maru** [comment]
@matsujirushi さん。

ありがとうございます！はじめてのIoT系で、まずそもそもの用語からイメージできない、いかんともしがたい状態でした。
ReButtonのIoT Plug and Play対応、楽しみにしております。

教えていただいた動画みて、色々試してみます。
